var preguntas = [
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple del verbo \"eat\"? / What is the simple past of the verb \"eat\"?",opciones:["eated","ate","eaten","eating"],correcta:1,explicacion:"La respuesta correcta es ate. Es la forma en pasado del verbo irregular eat."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado del verbo \"go\"? / What is the past participle of the verb \"go\"?",opciones:["went","goed","gone","going"],correcta:2,explicacion:"La respuesta correcta es gone. Es el participio pasado de go."},
{nivel:"Básico",pregunta:"Elige la forma correcta en presente simple: 'He ___ (play) soccer.'",opciones:["play","plays","playing","played"],correcta:1,explicacion:"Con he, she, it los verbos en presente llevan -s."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple del verbo \"buy\"?",opciones:["buyed","bought","buys","buying"],correcta:1,explicacion:"Pasado simple del verbo irregular buy."},
{nivel:"Básico",pregunta:"Elige la forma correcta en presente continuo: 'I am ___ (read) a book.'",opciones:["read","reads","reading","readed"],correcta:2,explicacion:"En presente continuo se usa am/is/are + verbo con -ing."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple del verbo \"swim\"?",opciones:["swimmed","swam","swum","swiming"],correcta:1,explicacion:"Pasado simple de swim: swam."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'They ___ (be) at the park yesterday.'",opciones:["are","was","were","is"],correcta:2,explicacion:"Con they se usa were en pasado."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple del verbo \"write\"?",opciones:["wrote","writed","written","writing"],correcta:0,explicacion:"Pasado de write: wrote."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'She ___ (drink) water every day.'",opciones:["drink","drinks","drinking","drank"],correcta:1,explicacion:"Con she se añade -s."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'speak'?",opciones:["spoke","speak","spoken","speaking"],correcta:2,explicacion:"Participio de speak: spoken."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'We ___ (not/go) to the party.'",opciones:["don't go","didn't go","not went","doesn't go"],correcta:1,explicacion:"Negativo en pasado: didn't + base."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple de 'run'?",opciones:["runned","ran","running","runs"],correcta:1,explicacion:"Pasado de run: ran."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'see'?",opciones:["saw","see","seen","seeing"],correcta:2,explicacion:"Participio de see: seen."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple de 'come'?",opciones:["came","comed","come","coming"],correcta:0,explicacion:"Pasado de come: came."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'He ___ (be) sick last week.'",opciones:["were","are","is","was"],correcta:3,explicacion:"Pasado de be con he: was."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'take'?",opciones:["took","taked","taken","taking"],correcta:2,explicacion:"Participio de take: taken."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'They ___ (clean) their room yesterday.'",opciones:["clean","cleans","cleaning","cleaned"],correcta:3,explicacion:"Pasado de clean: cleaned."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple de 'teach'?",opciones:["teached","teaches","teaching","taught"],correcta:3,explicacion:"Pasado de teach: taught."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'She ___ (buy) a gift for me.'",opciones:["buys","buy","bought","buying"],correcta:2,explicacion:"Pasado de buy: bought."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple de 'think'?",opciones:["thinked","thought","think","thinking"],correcta:1,explicacion:"Pasado de think: thought."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'She ___ (sing) a song now.'",opciones:["is singing","sings","sing","sang"],correcta:0,explicacion:"Presente continuo: is + -ing."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'write'?",opciones:["wrote","written","writing","writed"],correcta:1,explicacion:"Participio de write: written."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'I ___ (know) the answer yesterday.'",opciones:["knowed","knew","known","knowing"],correcta:1,explicacion:"Pasado de know: knew."},
{nivel:"Básico",pregunta:"¿Cuál es la forma correcta de 'study' para 'they' en presente?",opciones:["study","studys","studies","studying"],correcta:0,explicacion:"Con they no lleva -s."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple de 'break'?",opciones:["breaked","broke","broken","breaking"],correcta:1,explicacion:"Pasado de break: broke."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'He ___ (not/like) vegetables.'",opciones:["don't like","doesn't like","not like","didn't like"],correcta:1,explicacion:"Negativo presente: doesn't like."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'do'?",opciones:["did","does","done","doing"],correcta:2,explicacion:"Participio de do: done."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'We ___ (visit) our grandparents last Sunday.'",opciones:["visit","visits","visiting","visited"],correcta:3,explicacion:"Pasado de visit: visited."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple de 'bring'?",opciones:["brought","bringed","brang","bringing"],correcta:0,explicacion:"Pasado de bring: brought."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'sleep'?",opciones:["slept","sleeped","sleeping","sleep"],correcta:0,explicacion:"Participio de sleep: slept."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'I ___ (watch) TV right now.'",opciones:["watch","am watching","watched","watches"],correcta:1,explicacion:"Presente continuo: am watching."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple de 'say'?",opciones:["sayed","said","say","says"],correcta:1,explicacion:"Pasado de say: said."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'They ___ (be) tired after the match.'",opciones:["was","is","are","were"],correcta:3,explicacion:"Con they: were."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'drink'?",opciones:["drank","drinked","drunk","drinking"],correcta:2,explicacion:"Participio de drink: drunk."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'He ___ (cook) dinner yesterday.'",opciones:["cook","cooks","cooked","cooking"],correcta:2,explicacion:"Pasado de cook: cooked."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple de 'take'?",opciones:["taked","took","taken","taking"],correcta:1,explicacion:"Pasado de take: took."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'She ___ (not/see) the movie yet.'",opciones:["hasn't seen","doesn't see","don't see","didn't see"],correcta:0,explicacion:"Presente perfecto negativo: hasn't seen."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'win'?",opciones:["won","winned","wining","win"],correcta:0,explicacion:"Participio de win: won."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'keep'?",opciones:["keeped","kept","keeping","keep"],correcta:1,explicacion:"Participio de keep: kept."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'They ___ (be) in the cinema last night.'",opciones:["was","were","are","is"],correcta:1,explicacion:"Con they: were."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple de 'find'?",opciones:["finded","find","finding","found"],correcta:3,explicacion:"Pasado de find: found."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'She ___ (sing) beautifully yesterday.'",opciones:["singed","sang","sung","sings"],correcta:1,explicacion:"Pasado de sing: sang."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'give'?",opciones:["gave","gived","given","giving"],correcta:2,explicacion:"Participio de give: given."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'He ___ (drink) coffee an hour ago.'",opciones:["drank","drinked","drunk","drinks"],correcta:0,explicacion:"Pasado de drink: drank."},
{nivel:"Básico",pregunta:"¿Cuál es el pasado simple de 'feel'?",opciones:["feeled","felt","feeling","feel"],correcta:1,explicacion:"Pasado de feel: felt."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'We ___ (not/see) the accident yesterday.'",opciones:["didn't see","don't see","haven't seen","didn't saw"],correcta:0,explicacion:"Negativo pasado: didn't see."},
{nivel:"Básico",pregunta:"¿Cuál es el participio pasado de 'hide'?",opciones:["hided","hid","hidden","hiding"],correcta:2,explicacion:"Participio de hide: hidden."},
{nivel:"Básico",pregunta:"Elige la forma correcta: 'I ___ (be) at home all day.'",opciones:["was","were","am","are"],correcta:0,explicacion:"Con I, pasado: was."},
{nivel:"Básico",pregunta:'"Maria walks to her office..." ¿Cómo va María a trabajar?',opciones:["By foot","On foot","By walking","With feet"],correcta:1,explicacion:"A pie: on foot."},
{nivel:"Básico",pregunta:'"The family travels to the beach..." ¿Cómo viaja la familia?',opciones:["On plane","In plane","By plane","With plane"],correcta:2,explicacion:"by + transporte: by plane."},
{nivel:"Básico",pregunta:'"John goes downtown..." ¿Cómo se transporta?',opciones:["By car","In car","With car","By a car"],correcta:0,explicacion:"By car: en automóvil."},
{nivel:"Básico",pregunta:'"The students went on a field trip..." ¿Dónde estaban?',opciones:["By bus","On bus","In a bus","With a bus"],correcta:2,explicacion:"Estaban dentro del autobús: in a bus."},
{nivel:"Básico",pregunta:'"The tourists crossed the river..." ¿Cómo cruzaron?',opciones:["Through boat","By boat","With boat","In the boat"],correcta:1,explicacion:"By boat: en barco."},
{nivel:"Básico",pregunta:'"She loves riding to the park..." ¿Cómo va?',opciones:["By bicycle","On bicycle","On her bicycle","With bicycle"],correcta:2,explicacion:"On para bicicletas."},
{nivel:"Básico",pregunta:'"The businessmen arrived..." ¿Cómo llegaron?',opciones:["By taxi","In taxi","With a taxi","On taxi"],correcta:0,explicacion:"By taxi: en taxi."},
{nivel:"Básico",pregunta:'"We decided to travel across Europe..." ¿Cómo viajaron?',opciones:["On train","By train","In train","With train"],correcta:1,explicacion:"By train: en tren."},
{nivel:"Básico",pregunta:'"The pilot flew to the island..." ¿En qué viajó?',opciones:["By helicopter","On helicopter","With helicopter","In helicopter"],correcta:0,explicacion:"By helicopter: en helicóptero."},
{nivel:"Básico",pregunta:'"The children go to the park..." ¿Cómo van?',opciones:["By walking","with feet","By foot","On foot"],correcta:3,explicacion:"On foot: a pie."},
{nivel:"Intermedio",pregunta:'"The musicians were packing up..." ¿A qué hora empieza la fiesta?',opciones:["07:00 p. m.","08:00 p. m.","09:00 p. m.","It already finished"],correcta:3,explicacion:"El evento ya había terminado."},
{nivel:"Intermedio",pregunta:"The morning forecast predicted clear skies, but a sudden downpour...",opciones:["The weather changed unexpectedly","The forecast predicted heavy rain","People stayed at home","The office was closed"],correcta:0,explicacion:"El pronóstico decía despejado pero llovió."},
{nivel:"Intermedio",pregunta:'"He lives alone... Every night a loyal animal stays near the door." ¿Qué lo protege?',opciones:["His cat","His friends","Alone","His dog"],correcta:3,explicacion:"Un perro guardián es leal."},
{nivel:"Intermedio",pregunta:'"Her CV highlights that she can translate..." ¿Qué idiomas habla?',opciones:["Only English","English and French","English and Spanish","Only Spanish"],correcta:2,explicacion:"Traduce del Reino Unido a México: inglés y español."},
{nivel:"Intermedio",pregunta:'"The old rusty vehicle... the brand-new sports model..." ¿Qué carro es más rápido?',opciones:["The old car","The sports car","Both are equal","The silver car"],correcta:1,explicacion:"El deportivo es más rápido."},
{nivel:"Intermedio",pregunta:'"I am completely exhausted because my shift lasted twelve hours..." ¿Por qué está cansado?',opciones:["He slept well","He played all day","He ran all day","He worked all day"],correcta:3,explicacion:"Trabajó 12 horas."},
{nivel:"Intermedio",pregunta:'"The employees always secure the main entrance 60 minutes before mid-day." ¿A qué hora?',opciones:["09:00 a. m.","11:00 a. m.","12:00 p. m.","10:00 a. m."],correcta:1,explicacion:"12:00 - 1 hora = 11:00 AM."},
{nivel:"Intermedio",pregunta:'"My sister was born when the year reached its exact midpoint." ¿En qué mes?',opciones:["May","June","July","August"],correcta:2,explicacion:"Punto medio del año = julio."},
{nivel:"Intermedio",pregunta:'"She likes to sit quietly under the trees... carries a book..." ¿Cuál es su pasatiempo?',opciones:["Exercising","Cooking","Shopping","Reading"],correcta:3,explicacion:"Está leyendo un libro."},
{nivel:"Intermedio",pregunta:'"Every thermometer was breaking records as people crowded ice cream shops." ¿Cómo está el clima?',opciones:["Cold","Far","Big","Hot"],correcta:3,explicacion:"Hace calor."},
{nivel:"Intermedio",pregunta:'"Many people were shopping and it was difficult to move..." ¿Cómo estaba la tienda?',opciones:["Empty","Quiet","Crowded","Small"],correcta:2,explicacion:"Estaba llena de gente."},
{nivel:"Intermedio",pregunta:'"I am putting my salary into a savings account to explore Tokyo..." ¿Qué quiere hacer?',opciones:["Move to Japan","Travel to Japan","Work in Japan","Study in Japan"],correcta:1,explicacion:"Viajar a Japón."},
{nivel:"Intermedio",pregunta:'"There was ice on top of the pool..." ¿Cómo está el agua?',opciones:["The pool is dirty","The water is hot","The water is freezing","It is raining"],correcta:2,explicacion:"Agua congelada."},
{nivel:"Intermedio",pregunta:'"My cousin plays an electric instrument with six strings..." ¿Qué instrumento?',opciones:["Guitar","Drums","Piano","Violin"],correcta:0,explicacion:"Guitarra eléctrica de 6 cuerdas."},
{nivel:"Intermedio",pregunta:'"Her alarm rings exactly six hours after midnight..." ¿A qué hora se despierta?',opciones:["07:00 a. m.","06:00 a. m.","08:00 a. m.","05:00 a. m."],correcta:1,explicacion:"12 AM + 6 = 6:00 AM."},
{nivel:"Intermedio",pregunta:'"The bakery's creation was a success due to dark cacao from Belgium..." ¿Por qué?',opciones:["It is big","It has fruit","It uses high-quality cacao","It is warm"],correcta:2,explicacion:"Cacao de alta calidad."},
{nivel:"Intermedio",pregunta:'"I reached into my pockets only to find them empty; now I am locked out..." ¿Qué perdió?',opciones:["Wallet","Phone","Keys","Bag"],correcta:2,explicacion:"Perdió las llaves."},
{nivel:"Intermedio",pregunta:'"They are buying decorations and coordinate a gathering behind his back..." ¿Qué planean?',opciones:["A trip","A surprise party","A meeting","A movie night"],correcta:1,explicacion:"Fiesta sorpresa."},
{nivel:"Intermedio",pregunta:'"The train arrived late because there was a lot of snow on the tracks." ¿Por qué?',opciones:["Mechanical failure","Heavy snow","Accident","Traffic"],correcta:1,explicacion:"Nieve en vías."},
{nivel:"Intermedio",pregunta:'"He put on his warmest winter clothing because the temperature dropped below zero." ¿Qué usa?',opciones:["A t-shirt","A heavy coat","A sweater","A jacket"],correcta:1,explicacion:"Abrigo pesado."},
{nivel:"Intermedio",pregunta:'"She spends mornings wearing a white lab coat treating patients." ¿Su profesión?',opciones:["An artist","A teacher","A doctor","A nurse"],correcta:2,explicacion:"Es médica."},
{nivel:"Intermedio",pregunta:'"Our annual seaside vacation is the month after June." ¿Cuándo?',opciones:["June","July","August","September"],correcta:1,explicacion:"Julio."},
{nivel:"Intermedio",pregunta:'"The aroma of the freshly baked dessert filled the kitchen." ¿Cómo olía?',opciones:["Delicious","Bad","Sour","Burned"],correcta:0,explicacion:"Olía delicioso."},
{nivel:"Intermedio",pregunta:'"They bought their modern vehicle seven days ago." ¿Cuándo?',opciones:["Yesterday","Last month","Last week","Last year"],correcta:2,explicacion:"La semana pasada."},
{nivel:"Intermedio",pregunta:'"My parents have four children: sister, me, twin brothers." ¿Cuántos siblings?',opciones:["Two","Three","Four","One"],correcta:1,explicacion:"Hermana + 2 hermanos = 3 hermanos."},
{nivel:"Intermedio",pregunta:'"He was running to school looking at his watch." ¿Por qué?',opciones:["He is exercising","He is late for school","He is happy","He is scared"],correcta:1,explicacion:"Llega tarde a clases."},
{nivel:"Intermedio",pregunta:'"The film broadcasted from 19:00 to 21:00." ¿Duración?',opciones:["1 hour","4 hours","3 hours","2 hours"],correcta:3,explicacion:"2 horas."},
{nivel:"Intermedio",pregunta:'"Emma checked the fridge: no eggs, little milk, one slice of bread." ¿Problema?',opciones:["She was running out of food","The fridge was broken","The food was expensive","The kitchen was dirty"],correcta:0,explicacion:"Sin alimentos."},
{nivel:"Intermedio",pregunta:'"The top of the mountain was above the clouds." ¿Cómo es?',opciones:["Low","Flat","Small","High"],correcta:3,explicacion:"Montaña alta."},
{nivel:"Intermedio",pregunta:"The book talks about astronauts, rockets, and missions to other planets. ¿Tema?",opciones:["History","Space","Cooking","Animals"],correcta:1,explicacion:"El espacio."},
{nivel:"Intermedio",pregunta:"Emma leaves at 7:30. Class at 8:00. Arrives 10 min early. ¿Hora de llegada?",opciones:["07:30","08:10","07:50","08:00"],correcta:2,explicacion:"7:50 AM."},
{nivel:"Intermedio",pregunta:"My dog loves running and catches the ball first. ¿Cómo es?",opciones:["Slow","Lazy","Fast","Quiet"],correcta:2,explicacion:"Rápido."},
{nivel:"Intermedio",pregunta:"Daniel passes ball, practices shots, plays matches. ¿Deporte?",opciones:["Science","Fishing","Painting","Soccer"],correcta:3,explicacion:"Fútbol."},
{nivel:"Intermedio",pregunta:"Everyone in jackets, cold breeze. ¿Clima?",opciones:["Warm","Cold","Humid","Hot"],correcta:1,explicacion:"Hace frío."},
{nivel:"Intermedio",pregunta:"She wants to write an essay but has nothing to write with. ¿Qué necesita?",opciones:["Backpack","Ruler","Pen","Calculator"],correcta:2,explicacion:"Un bolígrafo."},
{nivel:"Intermedio",pregunta:"The park is beautiful when flowers bloom. ¿Cuándo?",opciones:["Spring","Winter","Summer","Autumn"],correcta:0,explicacion:"Primavera."},
{nivel:"Intermedio",pregunta:"He plans structures and designs bridges. ¿Profesión?",opciones:["Doctor","Teacher","Engineer","Architect"],correcta:2,explicacion:"Ingeniero."},
{nivel:"Intermedio",pregunta:"Sofia checks weather and carries umbrella when rain expected. ¿Por qué?",opciones:["To protect from rain","To carry books","To stay warm","To block sun"],correcta:0,explicacion:"Protegerse de la lluvia."},
{nivel:"Intermedio",pregunta:"¿Opuesto de \"hot\"?",opciones:["Cold","Big","Old","Fast"],correcta:0,explicacion:"Cold."},
{nivel:"Intermedio",pregunta:"Departure at 10:00, be at station quarter to ten. ¿Hora?",opciones:["10:00","09:30","09:45","09:55"],correcta:2,explicacion:"9:45 AM."},
{nivel:"Intermedio",pregunta:'"My dog has a coat like chocolate." ¿Color?',opciones:["Black","White","Grey","Brown"],correcta:3,explicacion:"Marrón."},
{nivel:"Intermedio",pregunta:"He joins his team every weekend after Friday night. ¿Cuándo?",opciones:["Every day","Every Sunday","Every Friday","Every Saturday"],correcta:3,explicacion:"Sábado."},
{nivel:"Intermedio",pregunta:"Indoor temperature dropped because windows were open. ¿Qué pasó?",opciones:["Temp decreased","Lights went out","Furniture moved","Garden watered"],correcta:0,explicacion:"Temperatura bajó."},
{nivel:"Intermedio",pregunta:"Carlos going on 3-day trip. ¿Objeto más útil?",opciones:["Pillow","Clock","Suitcase","Spoon"],correcta:2,explicacion:"Maleta."},
{nivel:"Intermedio",pregunta:"Park is beautiful 3rd month of year. ¿Cuándo?",opciones:["Summer","Winter","Spring","Autumn"],correcta:2,explicacion:"Primavera."},
{nivel:"Intermedio",pregunta:"He spent 5 years calculating structures; supervises highway overpasses. ¿Qué es?",opciones:["Engineer","Teacher","Doctor","Architect"],correcta:0,explicacion:"Ingeniero."},
{nivel:"Intermedio",pregunta:"Extracts fresh liquid from citrus for morning meal. ¿Qué prepara?",opciones:["Apple juice","Orange juice","Milk","Coffee"],correcta:1,explicacion:"Jugo de naranja."},
{nivel:"Intermedio",pregunta:"Sand was very hot. Opposite of hot?",opciones:["Cold","Big","Old","Fast"],correcta:0,explicacion:"Cold."},
{nivel:"Intermedio",pregunta:"Used device to write docs, browse internet, send emails. ¿Qué usó?",opciones:["Phone","Computer","Tablet","Chair"],correcta:1,explicacion:"Computadora."},
{nivel:"Intermedio",pregunta:"Farmer with sheep, loyal animal helps protect. ¿Qué animal?",opciones:["Lion","Shark","Dog","Elephant"],correcta:2,explicacion:"Perro."},
{nivel:"Intermedio",pregunta:"Poured oat flakes, added almond milk. ¿Desayuno?",opciones:["Toast","Cereal","Soup","Salad"],correcta:1,explicacion:"Cereal."},
{nivel:"Intermedio",pregunta:"Parents celebrated anniversary, the other son helped organize. ¿Parentesco?",opciones:["Cousin","Grandson","Friend","Brother"],correcta:3,explicacion:"Hermano."},
{nivel:"Avanzado",pregunta:"All financial transactions in NYC used local currency. ¿Cuál?",opciones:["Peso","Euro","Dollar","Yen"],correcta:2,explicacion:"Dólar (Nueva York)."},
{nivel:"Avanzado",pregunta:"Dark clouds appeared, people opened something to protect from rain. ¿Qué?",opciones:["Sunglasses","Swimsuit","Shorts","Umbrella"],correcta:3,explicacion:"Paraguas."},
{nivel:"Avanzado",pregunta:"Workers demotivated when first 24 hours of workweek begin. ¿Día?",opciones:["Sunday","Monday","Tuesday","Wednesday"],correcta:1,explicacion:"Lunes."},
{nivel:"Avanzado",pregunta:"He needed to write a note, picked up something with a point. ¿Qué?",opciones:["Eraser","Pencil","Book","Ruler"],correcta:1,explicacion:"Lápiz."},
{nivel:"Avanzado",pregunta:"Child smiled from ear to ear when surprised with a gift. ¿Cómo se sentía?",opciones:["Happy","Sad","Angry","Tired"],correcta:0,explicacion:"Feliz."},
{nivel:"Avanzado",pregunta:"Daily schedule: educational lesson plans, in front of classroom. ¿Profesión?",opciones:["Teacher","Artist","Farmer","Pilot"],correcta:0,explicacion:"Maestra."},
{nivel:"Avanzado",pregunta:"Turns off light, gets in bed, closes eyes. ¿Preparándose para?",opciones:["Wake up","Have breakfast","Go to bed","Run"],correcta:2,explicacion:"Dormir."},
{nivel:"Avanzado",pregunta:"Living things in water so small only visible with microscope. ¿Adjetivo?",opciones:["Huge","Tiny","Tall","Wide"],correcta:1,explicacion:"Diminutos."},
{nivel:"Avanzado",pregunta:"She cut paper using a tool with two blades. ¿Qué usó?",opciones:["Scissors","Glue","Ruler","Pen"],correcta:0,explicacion:"Tijeras."},
{nivel:"Avanzado",pregunta:"Mother tells stories about the man who raised her. ¿Quién?",opciones:["Father","Uncle","Grandfather","Brother"],correcta:2,explicacion:"Abuelo."},
{nivel:"Avanzado",pregunta:"Very hot, people turned on AC. ¿Estación?",opciones:["Winter","Autumn","Spring","Summer"],correcta:3,explicacion:"Verano."},
{nivel:"Avanzado",pregunta:"Sun very bright, she put on something to protect eyes. ¿Qué?",opciones:["Glasses","Sunglasses","Hat","Gloves"],correcta:1,explicacion:"Lentes de sol."},
{nivel:"Avanzado",pregunta:"Person has 5 fingers on one hand. Fingers on both hands?",opciones:["One","Twelve","Ten","Twenty"],correcta:2,explicacion:"Diez."},
{nivel:"Avanzado",pregunta:"Many cars on road, drivers spent long time moving short distance. ¿Cómo se movían?",opciones:["Slow","Quick","Easy","Short"],correcta:0,explicacion:"Lento."},
{nivel:"Avanzado",pregunta:"She needed milk, bread, fruits, vegetables. ¿Qué tienda?",opciones:["Clothing store","Grocery store","Toy store","Bank"],correcta:1,explicacion:"Supermercado."},
{nivel:"Avanzado",pregunta:"The other daughter of my parents studied corporate law. ¿Parentesco?",opciones:["Mother","Aunt","Sister","Cousin"],correcta:2,explicacion:"Hermana."},
{nivel:"Avanzado",pregunta:"Finished typing, closed device, put in backpack. ¿Qué dispositivo?",opciones:["A car","A mobile computer","A chair","A book"],correcta:1,explicacion:"Laptop."},
{nivel:"Avanzado",pregunta:"Covered eyes, identified object by sound. ¿Parte del cuerpo?",opciones:["Ears","Hands","Eyes","Feet"],correcta:0,explicacion:"Oídos."},
{nivel:"Avanzado",pregunta:"Day was clear, no clouds. ¿Color del cielo?",opciones:["Blue","Green","Purple","Pink"],correcta:0,explicacion:"Azul."},
{nivel:"Avanzado",pregunta:"Workers happy because weekend about to begin. ¿Día?",opciones:["Thursday","Friday","Saturday","Sunday"],correcta:1,explicacion:"Viernes."},
{nivel:"Avanzado",pregunta:"She made salad with green leaves. ¿Ingrediente?",opciones:["Lettuce","Chocolate","Sugar","Ice cream"],correcta:0,explicacion:"Lechuga."},
{nivel:"Avanzado",pregunta:"Works in restaurant, prepares meals. ¿Quién?",opciones:["Driver","Cook","Doctor","Chef"],correcta:3,explicacion:"Chef."},
{nivel:"Avanzado",pregunta:"Trees had no leaves, ice forming on lake. ¿Estación?",opciones:["Summer","Spring","Autumn","Winter"],correcta:3,explicacion:"Invierno."},
{nivel:"Avanzado",pregunta:"Animal sleeps many hours, climbs, kept as pet. ¿Animal?",opciones:["Cat","Dog","Bird","Fish"],correcta:0,explicacion:"Gato."},
{nivel:"Avanzado",pregunta:"Ten groups, ten items each. ¿Número total?",opciones:["10","50","100","1000"],correcta:2,explicacion:"100."},
{nivel:"Avanzado",pregunta:"Alarm rang early, time to go back to school after weekend. ¿Día?",opciones:["Tuesday","Monday","Friday","Sunday"],correcta:1,explicacion:"Lunes."},
{nivel:"Avanzado",pregunta:"She smiled after hearing good news. ¿Cómo se siente?",opciones:["Table","Happy","School","Car"],correcta:1,explicacion:"Feliz."},
{nivel:"Avanzado",pregunta:"Mother's brother funded family reunion. ¿Parentesco?",opciones:["Aunt","Cousin","Uncle","Nephew"],correcta:2,explicacion:"Tío."},
{nivel:"Avanzado",pregunta:"Reviewed menu, ordered with waiter, waited for chef. ¿Acción principal?",opciones:["Eat","Drive","Dance","Sleep"],correcta:0,explicacion:"Comer."},
{nivel:"Avanzado",pregunta:"Put head on pillow, lay down to rest. ¿Mueble?",opciones:["Desk","Bed","Chair","Sofa"],correcta:1,explicacion:"Cama."},
{nivel:"Avanzado",pregunta:"Dark clouds, heavy rain. ¿Actividad más difícil?",opciones:["Reading indoors","Cooking","Riding a bicycle","Watching TV"],correcta:2,explicacion:"Andar en bici bajo la lluvia."},
{nivel:"Avanzado",pregunta:"Historic institution with cataloged manuscripts, silence required. ¿Lugar?",opciones:["Bookstore","Library","School","Museum"],correcta:1,explicacion:"Biblioteca."},
{nivel:"Avanzado",pregunta:"Animal spends entire life in water. ¿Tipo?",opciones:["Cat","Dog","Fish","Bird"],correcta:2,explicacion:"Pez."},
{nivel:"Avanzado",pregunta:"Building was very large. Opuesto de large?",opciones:["Small","Fast","Hot","Old"],correcta:0,explicacion:"Small."},
{nivel:"Avanzado",pregunta:"Each student ___ to school by bus. Completa:",opciones:["go","goes","going","gone"],correcta:1,explicacion:"Each = third person singular: goes."},
{nivel:"Avanzado",pregunta:"Students like healthy food but ___ eat veggies every day.",opciones:["don't","doesn't","not","isn't"],correcta:0,explicacion:"They = plural: don't."},
{nivel:"Avanzado",pregunta:"___ you speak English fluently?",opciones:["Does","Is","Do","Are"],correcta:2,explicacion:"Do (pregunta con you)."},
{nivel:"Avanzado",pregunta:"I ___ happy to see my friends.",opciones:["is","are","am","be"],correcta:2,explicacion:"I am."},
{nivel:"Avanzado",pregunta:"That office across the hall is ___ personal workspace.",opciones:["his","he","him","he's"],correcta:0,explicacion:"His = posesivo."},
{nivel:"Avanzado",pregunta:"My backpack is ___ than my brother's.",opciones:["big","bigger","more big","biggest"],correcta:1,explicacion:"Comparativo: bigger."},
{nivel:"Avanzado",pregunta:"There are three ___ playing in the park.",opciones:["childs","child","childes","children"],correcta:3,explicacion:"Plural irregular: children."},
{nivel:"Avanzado",pregunta:"Look! It ___ heavily right now.",opciones:["rain","is raining","rains","raining"],correcta:1,explicacion:"Presente continuo: is raining."},
{nivel:"Avanzado",pregunta:"I ___ read complex articles when I was 5.",opciones:["can","could","able","was"],correcta:1,explicacion:"Could = habilidad en pasado."},
{nivel:"Avanzado",pregunta:"I want to eat ___ apple.",opciones:["an","a","the","some"],correcta:0,explicacion:"An + sonido vocálico."},
{nivel:"Avanzado",pregunta:"Where ___ you born?",opciones:["did","were","was","are"],correcta:1,explicacion:"Were born."},
{nivel:"Avanzado",pregunta:"There ___ a pen on the table.",opciones:["are","is","be","am"],correcta:1,explicacion:"There is (singular)."},
{nivel:"Avanzado",pregunta:"___ we go to the cinema? (sugerencia)",opciones:["Do","Are","Does","Shall"],correcta:3,explicacion:"Shall we...? sugerencia."},
{nivel:"Avanzado",pregunta:"She doesn't ___ any siblings.",opciones:["has","having","have","had"],correcta:2,explicacion:"Doesn't + base form: have."},
{nivel:"Avanzado",pregunta:"___ are my books (objetos lejos).",opciones:["These","This","Those","That"],correcta:2,explicacion:"Those = lejos, plural."},
{nivel:"Avanzado",pregunta:"This is the ___ book I've read.",opciones:["good","better","best","goodest"],correcta:2,explicacion:"Superlativo: best."},
{nivel:"Avanzado",pregunta:"She is talking to ___.",opciones:["he","him","his","he's"],correcta:1,explicacion:"Objeto: him."},
{nivel:"Avanzado",pregunta:"You ___ smoke here (prohibición).",opciones:["mustn't","can","don't","might"],correcta:0,explicacion:"Mustn't = prohibido."},
{nivel:"Avanzado",pregunta:"I ___ to the cinema last night.",opciones:["go","goes","went","gone"],correcta:2,explicacion:"Went (pasado de go)."},
{nivel:"Avanzado",pregunta:"___ do you live?",opciones:["What","Who","Where","When"],correcta:2,explicacion:"Where = lugar."},
{nivel:"Avanzado",pregunta:"They ___ TV when the phone rang.",opciones:["was watching","watch","watched","were watching"],correcta:3,explicacion:"They + were watching."},
{nivel:"Avanzado",pregunta:"I ___ visit my grandmother tomorrow (plan).",opciones:["am going to","go","will","going"],correcta:0,explicacion:"Be going to = plan futuro."},
{nivel:"Avanzado",pregunta:"She ___ a new car (have got).",opciones:["have got","has got","having got","has"],correcta:1,explicacion:"Has got (3ra persona)."},
{nivel:"Avanzado",pregunta:"How ___ apples do we need?",opciones:["much","many","any","some"],correcta:1,explicacion:"How many + contables plural."},
{nivel:"Avanzado",pregunta:"You ___ do your homework (obligación).",opciones:["must","might","can","could"],correcta:0,explicacion:"Must = obligación."},
{nivel:"Avanzado",pregunta:"If it rains, we ___ home.",opciones:["stay","stayed","will stay","would stay"],correcta:2,explicacion:"Will + condicional."},
{nivel:"Avanzado",pregunta:"How about ___ to the park?",opciones:["go","went","to go","going"],correcta:3,explicacion:"How about + -ing."},
{nivel:"Avanzado",pregunta:"We love ___ new teacher.",opciones:["our","us","ours","we"],correcta:0,explicacion:"Adjetivo posesivo: our."},
{nivel:"Avanzado",pregunta:"I ___ drink coffee (dislike).",opciones:["always","usually","often","never"],correcta:3,explicacion:"Never = nunca."},
{nivel:"Avanzado",pregunta:"Class starts ___ 8:00 AM.",opciones:["in","on","at","to"],correcta:2,explicacion:"At + hora."},
{nivel:"Avanzado",pregunta:"She ___ finished her project yet.",opciones:["hasn't","haven't","don't","doesn't"],correcta:0,explicacion:"Hasn't (present perfect)."},
{nivel:"Avanzado",pregunta:"___ quiet, please (orden).",opciones:["Be","Are","Is","Being"],correcta:0,explicacion:"Imperativo: Be."},
{nivel:"Avanzado",pregunta:"Participio pasado de eat?",opciones:["eat","eated","ate","eaten"],correcta:3,explicacion:"Eaten."},
{nivel:"Avanzado",pregunta:"This pen is mine, not ___.",opciones:["you","your","yours","you're"],correcta:2,explicacion:"Posesivo: yours."},
{nivel:"Avanzado",pregunta:"There is ___ water in the bottle.",opciones:["many","some","any","few"],correcta:1,explicacion:"Some + incontables."},
{nivel:"Avanzado",pregunta:"___ did you go yesterday?",opciones:["What","When","Where","All of them"],correcta:2,explicacion:"Where = lugar."},
{nivel:"Avanzado",pregunta:"He ___ work on Saturdays.",opciones:["don't","isn't","doesn't","aren't"],correcta:2,explicacion:"Doesn't (3ra persona)."},
{nivel:"Avanzado",pregunta:"I ___ my homework last night.",opciones:["finished","finish","finishing","finishes"],correcta:0,explicacion:"Pasado: finished."},
{nivel:"Avanzado",pregunta:"She is the ___ girl in class.",opciones:["tall","taller","tallest","more tall"],correcta:2,explicacion:"Superlativo: tallest."},
{nivel:"Avanzado",pregunta:"Let's ___ to music.",opciones:["listen","listens","listening","listened"],correcta:0,explicacion:"Let's + base form."},
{nivel:"Avanzado",pregunta:"They ___ to the park last weekend.",opciones:["go","went","gone","going"],correcta:1,explicacion:"Went (pasado de go)."},
{nivel:"Avanzado",pregunta:"She ___ a book right now.",opciones:["read","reads","is reading","readed"],correcta:2,explicacion:"Presente continuo: is reading."},
{nivel:"Avanzado",pregunta:"This movie is ___ than the other.",opciones:["good","gooder","best","better"],correcta:3,explicacion:"Comparativo: better."},
{nivel:"Avanzado",pregunta:"I saw Sarah but didn't talk to ___.",opciones:["she","her","hers","she's"],correcta:1,explicacion:"Object pronoun: her."},
{nivel:"Avanzado",pregunta:"Auxiliar para preguntas y negaciones en pasado simple?",opciones:["do","does","did","is"],correcta:2,explicacion:"Did."},
{nivel:"Avanzado",pregunta:"The people ___ waiting outside.",opciones:["were","was","is","has"],correcta:0,explicacion:"People = plural: were."},
{nivel:"Avanzado",pregunta:"I bought ___ apples.",opciones:["any","some","much","a"],correcta:1,explicacion:"Some (afirmativo, plural)."},
{nivel:"Avanzado",pregunta:"Contracción de they are?",opciones:["theyr","their","there're","they're"],correcta:3,explicacion:"They're."},
{nivel:"Avanzado",pregunta:"She ___ speak three languages (habilidad).",opciones:["can","can't","is","do"],correcta:0,explicacion:"Can = habilidad."},
{nivel:"Avanzado",pregunta:"Turn ___ the lights before leaving.",opciones:["in","off","up","at"],correcta:1,explicacion:"Turn off = apagar."},
{nivel:"Avanzado",pregunta:"The child was running and suddenly ___ on the wet sidewalk.",opciones:["fell down","falls down","falling down","fall down"],correcta:0,explicacion:"Fell down = se cayó."},
{nivel:"Avanzado",pregunta:"The boy was riding his bike and ___ off after hitting a rock.",opciones:["falls off","fall off","falling off","fell off"],correcta:3,explicacion:"Fell off = se cayó de."},
{nivel:"Avanzado",pregunta:"Workers used a machine to ___ the old wall.",opciones:["bring down","bring up","bring out","bring back"],correcta:0,explicacion:"Bring down = derribar."}
];
